// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Footer: typeof import('./components/Footer.vue')['default'];
    Logos: typeof import('./components/Logos.vue')['default'];
    QBtn: typeof import('quasar')['QBtn'];
    QHeader: typeof import('quasar')['QHeader'];
    QIcon: typeof import('quasar')['QIcon'];
    QLayout: typeof import('quasar')['QLayout'];
    QPage: typeof import('quasar')['QPage'];
    QPageContainer: typeof import('quasar')['QPageContainer'];
    QRouteTab: typeof import('quasar')['QRouteTab'];
    QTabs: typeof import('quasar')['QTabs'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    VitalWelcome: typeof import('./components/VitalWelcome.vue')['default'];
  }
}

export {};
